name: sixam_mart_store
description: An application for multivendor ecommerce restaurant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.5
  flutter_typeahead: ^4.3.7
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
  flutter_inappwebview: ^5.7.1
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.2
  http: ^0.13.4
  phone_number: ^1.0.0
  country_code_picker: ^3.0.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  dotted_border: ^2.0.0+1
  intl: 0.19.0
  just_the_tooltip: ^0.0.12
  audioplayers: ^6.0.0
  flutter_switch: ^0.3.2
  cupertino_icons: ^1.0.2
  vibration: ^1.7.6
  bluetooth_thermal_printer: ^0.0.6
  win32: ^5.5.1
  esc_pos_printer: ^4.1.0
  esc_pos_bluetooth: ^0.4.1
  flutter_blue: ^0.8.0
  printing: ^5.9.3
#  flutter_pos_printer_platform: ^1.4.2
  esc_pos_utils: ^1.1.0
  screenshot: ^3.0.0
  http_parser: ^4.0.2
  path: ^1.8.1
  image: ^3.0.2


dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/notification.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900